# Generated by Django 3.1.7 on 2021-03-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['target_name'], 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name_plural': 'Memberships'},
        ),
        migrations.AddField(
            model_name='challenge',
            name='join_type',
            field=models.CharField(choices=[('OP', 'Open'), ('AP', 'Approval'), ('IN', 'Invite'), ('CL', 'Closed')], default='OP', max_length=2),
        ),
        migrations.AddField(
            model_name='challenge',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='membership',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
