# Generated by Django 3.1.7 on 2021-03-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20210307_2344'),
        ('challenges', '0005_challenge_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='activities',
            field=models.ManyToManyField(related_name='challenges', through='challenges.Contribution', to='activities.Activity'),
        ),
    ]
