# Generated by Django 3.1.7 on 2021-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20210307_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='target_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Target date'),
        ),
    ]
