# Generated by Django 3.1.7 on 2021-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20210310_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Notification Sent'),
        ),
    ]
