# Generated by Django 3.1.7 on 2021-03-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relate_activities',
            field=models.BooleanField(default=True),
        ),
    ]
