# Generated by Django 3.1.7 on 2021-05-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_relate_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_distances',
            field=models.BooleanField(default=True),
        ),
    ]
