# Generated by Django 3.1.7 on 2021-03-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20210307_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='original_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='provider',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
