# Generated by Django 3.1.7 on 2021-03-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='original_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
