# Generated by Django 3.1.7 on 2021-07-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
