# Generated by Django 3.1.7 on 2022-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20210705_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='used_internal_conversion',
            field=models.BooleanField(default=False, verbose_name='Internal Distance Converted'),
        ),
    ]
